server:
  port: 42069
  cors:
    allow-credentials: on
    allowed-origins:
      - 'http://*'
      - 'https://*'
    allowed-headers:
      - Authorization
      - Content-Type
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS

spring:
  security:
    oauth2:
      client:
        registration:
          zitadel:
            client-id: 305351145696591875
            client-secret: 305351145696591875
            scope:
              - openid
              - profile
              - email
            client-authentication-method: none
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          zitadel:
            issuer-uri: http://localhost:8080/
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/
